//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoTrello.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requisito()
        {
            this.requisitos1 = new HashSet<requisito>();
            this.trabajoes = new HashSet<trabajo>();
            this.sprints = new HashSet<sprint>();
        }
    
        public int idRequisitos { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string Tipo { get; set; }
        public short Prioridad { get; set; }
        public short Puntos { get; set; }
        public short Estado { get; set; }
        public int idInformador { get; set; }
        public Nullable<int> idResponsable { get; set; }
        public int idProyecto { get; set; }
        public Nullable<int> idRequisitosPadre { get; set; }
        public Nullable<System.DateTime> TiempoEstimado { get; set; }
        public Nullable<System.DateTime> fechacreado { get; set; }
    
        public virtual proyecto proyecto { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requisito> requisitos1 { get; set; }
        public virtual requisito requisito1 { get; set; }
        public virtual usuario usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trabajo> trabajoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sprint> sprints { get; set; }
    }
}
