//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoTrello.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trabajo
    {
        public int idTrabajo { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public decimal Tiempotrabajada { get; set; }
        public string Comentario { get; set; }
        public System.DateTime Fechaguardado { get; set; }
        public int idRequisitos { get; set; }
        public int idUsuario { get; set; }
    
        public virtual requisito requisito { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
