//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoTrello.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class proyectoTrelloEntities : DbContext
    {
        public proyectoTrelloEntities()
            : base("name=proyectoTrelloEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<proyecto> proyectoes { get; set; }
        public virtual DbSet<ProyectoUsuario> ProyectoUsuarios { get; set; }
        public virtual DbSet<requisito> requisitos { get; set; }
        public virtual DbSet<RequisitosEstado> RequisitosEstadoes { get; set; }
        public virtual DbSet<rol> rols { get; set; }
        public virtual DbSet<sprint> sprints { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<trabajo> trabajoes { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
    }
}
